Fix build issues with boost 1.87 (#377)
With boost 1.87, some calls to spawn() generate this error:

error: ignoring returned value of type 'boost::asio::
deferred_async_operation<void(std::__exception_ptr::exception_ptr),
boost::asio::detail::initiate_spawn<boost::asio::io_context::
basic_executor_type<std::allocator<void>, 0> >...', declared with
attribute 'nodiscard' [-Werror=unused-result]

This works around the error by voiding the return.

Signed-off-by: Jason M. Bills <jason.m.bills@intel.com>